import { Spot } from '@/types'

export const DEMO_SPOTS: Spot[] = [
  {
    id: '1',
    name: 'Joe Coffee Waverly',
    slug: 'joe-coffee-waverly-nyc',
    type: 'coffee_shop',
    address: '141 Waverly Pl, New York, NY 10014',
    city: 'New York City',
    neighborhood: 'Greenwich Village',
    lat: 40.731228,
    lng: -74.000608,
    google_place_id: null,
    photos: [
      { url: 'https://images.unsplash.com/photo-1501339847302-ac426a4a7cbb?w=800', caption: 'Interior' },
      { url: 'https://images.unsplash.com/photo-1554118811-1e0d58224f24?w=800', caption: 'Counter' },
    ],
    hours: {
      monday: { open: '07:00', close: '20:00' },
      tuesday: { open: '07:00', close: '20:00' },
      wednesday: { open: '07:00', close: '20:00' },
      thursday: { open: '07:00', close: '20:00' },
      friday: { open: '07:00', close: '20:00' },
      saturday: { open: '08:00', close: '20:00' },
      sunday: { open: '08:00', close: '19:00' },
    },
    work_score: 8.2,
    late_night_score: 5.0,
    wifi_score: 8.5,
    outlet_score: 7.0,
    noise_score: 6.0,
    seating_score: 7.5,
    has_wifi: true,
    has_outlets: true,
    laptop_friendly: true,
    has_bathroom: true,
    has_food: true,
    has_drinks: true,
    noise_level: 'moderate',
    seating_comfort: 'good',
    vibe_tags: ['cozy', 'specialty coffee', 'laptop ok', 'no time limit'],
    notes: 'Great espresso. Good natural light. Fills up fast on weekends.',
    status: 'approved',
    submitted_by: null,
    created_at: new Date().toISOString(),
    last_verified_at: null,
    workability_score: null,
    workability_reasoning: null,
    workability_scored_at: null,
    updated_at: new Date().toISOString(),
  },
  {
    id: '2',
    name: 'Bushwick Grind',
    slug: 'bushwick-grind-nyc',
    type: 'coffee_shop',
    address: '230 Wyckoff Ave, Brooklyn, NY 11237',
    city: 'New York City',
    neighborhood: 'Bushwick',
    lat: 40.703512,
    lng: -73.923801,
    google_place_id: null,
    photos: [
      { url: 'https://images.unsplash.com/photo-1509042239860-f550ce710b93?w=800', caption: 'Bar area' },
    ],
    hours: {
      monday: { open: '07:00', close: '23:00' },
      tuesday: { open: '07:00', close: '23:00' },
      wednesday: { open: '07:00', close: '23:00' },
      thursday: { open: '07:00', close: '00:00' },
      friday: { open: '07:00', close: '02:00' },
      saturday: { open: '09:00', close: '02:00' },
      sunday: { open: '09:00', close: '22:00' },
    },
    work_score: 7.8,
    late_night_score: 9.0,
    wifi_score: 7.5,
    outlet_score: 8.5,
    noise_score: 6.0,
    seating_score: 7.0,
    has_wifi: true,
    has_outlets: true,
    laptop_friendly: true,
    has_bathroom: true,
    has_food: true,
    has_drinks: true,
    noise_level: 'moderate',
    seating_comfort: 'good',
    vibe_tags: ['industrial', 'late night', 'loud weekends', 'outlets everywhere'],
    notes: 'Stays open late Thu–Sat. Beer + coffee. Good outlet situation.',
    status: 'approved',
    submitted_by: null,
    created_at: new Date().toISOString(),
    last_verified_at: null,
    workability_score: null,
    workability_reasoning: null,
    workability_scored_at: null,
    updated_at: new Date().toISOString(),
  },
  {
    id: '3',
    name: 'The Late Lobby',
    slug: 'the-late-lobby-nyc',
    type: 'hotel_lobby',
    address: '485 7th Ave, New York, NY 10018',
    city: 'New York City',
    neighborhood: 'Midtown',
    lat: 40.750832,
    lng: -73.993401,
    google_place_id: null,
    photos: [
      { url: 'https://images.unsplash.com/photo-1564501049412-61c2a3083791?w=800', caption: 'Lobby' },
      { url: 'https://images.unsplash.com/photo-1582719478250-c89cae4dc85b?w=800', caption: 'Seating' },
    ],
    hours: {
      monday: { open: '00:00', close: '23:59' },
      tuesday: { open: '00:00', close: '23:59' },
      wednesday: { open: '00:00', close: '23:59' },
      thursday: { open: '00:00', close: '23:59' },
      friday: { open: '00:00', close: '23:59' },
      saturday: { open: '00:00', close: '23:59' },
      sunday: { open: '00:00', close: '23:59' },
    },
    work_score: 6.5,
    late_night_score: 9.8,
    wifi_score: 8.0,
    outlet_score: 9.0,
    noise_score: 8.5,
    seating_score: 9.0,
    has_wifi: true,
    has_outlets: true,
    laptop_friendly: true,
    has_bathroom: true,
    has_food: false,
    has_drinks: true,
    noise_level: 'quiet',
    seating_comfort: 'excellent',
    vibe_tags: ['24hr', 'hotel lobby', 'quiet', 'business traveler', 'power everywhere'],
    notes: '24-hour hotel lobby. AC everywhere. Staff never bothers you. Bring your own snacks.',
    status: 'approved',
    submitted_by: null,
    created_at: new Date().toISOString(),
    last_verified_at: null,
    workability_score: null,
    workability_reasoning: null,
    workability_scored_at: null,
    updated_at: new Date().toISOString(),
  },
  {
    id: '4',
    name: 'Veselka',
    slug: 'veselka-nyc',
    type: 'diner',
    address: '144 2nd Ave, New York, NY 10003',
    city: 'New York City',
    neighborhood: 'East Village',
    lat: 40.728401,
    lng: -73.986901,
    google_place_id: null,
    photos: [
      { url: 'https://images.unsplash.com/photo-1414235077428-338989a2e8c0?w=800', caption: 'Dining room' },
    ],
    hours: {
      monday: { open: '00:00', close: '23:59' },
      tuesday: { open: '00:00', close: '23:59' },
      wednesday: { open: '00:00', close: '23:59' },
      thursday: { open: '00:00', close: '23:59' },
      friday: { open: '00:00', close: '23:59' },
      saturday: { open: '00:00', close: '23:59' },
      sunday: { open: '00:00', close: '23:59' },
    },
    work_score: 7.0,
    late_night_score: 9.5,
    wifi_score: 5.0,
    outlet_score: 6.0,
    noise_score: 5.5,
    seating_score: 7.0,
    has_wifi: true,
    has_outlets: true,
    laptop_friendly: true,
    has_bathroom: true,
    has_food: true,
    has_drinks: true,
    noise_level: 'moderate',
    seating_comfort: 'good',
    vibe_tags: ['24hr', 'Ukrainian diner', 'classic NYC', 'late night food'],
    notes: 'NYC institution. Open 24 hours. Wifi is spotty but the pierogi are worth it.',
    status: 'approved',
    submitted_by: null,
    created_at: new Date().toISOString(),
    last_verified_at: null,
    workability_score: null,
    workability_reasoning: null,
    workability_scored_at: null,
    updated_at: new Date().toISOString(),
  },
  {
    id: '5',
    name: 'Intelligentsia Silver Lake',
    slug: 'intelligentsia-silver-lake-la',
    type: 'coffee_shop',
    address: '3922 W Sunset Blvd, Los Angeles, CA 90029',
    city: 'Los Angeles',
    neighborhood: 'Silver Lake',
    lat: 34.090301,
    lng: -118.270401,
    google_place_id: null,
    photos: [
      { url: 'https://images.unsplash.com/photo-1495474472287-4d71bcdd2085?w=800', caption: 'Espresso bar' },
      { url: 'https://images.unsplash.com/photo-1453614512568-c4024d13c247?w=800', caption: 'Seating' },
    ],
    hours: {
      monday: { open: '06:00', close: '20:00' },
      tuesday: { open: '06:00', close: '20:00' },
      wednesday: { open: '06:00', close: '20:00' },
      thursday: { open: '06:00', close: '20:00' },
      friday: { open: '06:00', close: '20:00' },
      saturday: { open: '07:00', close: '20:00' },
      sunday: { open: '07:00', close: '20:00' },
    },
    work_score: 8.5,
    late_night_score: 4.0,
    wifi_score: 8.8,
    outlet_score: 7.5,
    noise_score: 7.5,
    seating_score: 7.5,
    has_wifi: true,
    has_outlets: true,
    laptop_friendly: true,
    has_bathroom: true,
    has_food: false,
    has_drinks: true,
    noise_level: 'quiet',
    seating_comfort: 'good',
    vibe_tags: ['specialty coffee', 'sunny', 'patio', 'influencer crowd'],
    notes: 'Beautiful light in the morning. Patio seating. Gets crowded but table turnover is fast.',
    status: 'approved',
    submitted_by: null,
    created_at: new Date().toISOString(),
    last_verified_at: null,
    workability_score: null,
    workability_reasoning: null,
    workability_scored_at: null,
    updated_at: new Date().toISOString(),
  },
  {
    id: '6',
    name: 'Night Owl Diner',
    slug: 'night-owl-diner-la',
    type: 'diner',
    address: '5601 Hollywood Blvd, Los Angeles, CA 90028',
    city: 'Los Angeles',
    neighborhood: 'Hollywood',
    lat: 34.101801,
    lng: -118.316401,
    google_place_id: null,
    photos: [
      { url: 'https://images.unsplash.com/photo-1567521464027-f127ff144326?w=800', caption: 'Counter' },
    ],
    hours: {
      monday: { open: '06:00', close: '02:00' },
      tuesday: { open: '06:00', close: '02:00' },
      wednesday: { open: '06:00', close: '02:00' },
      thursday: { open: '06:00', close: '03:00' },
      friday: { open: '00:00', close: '23:59' },
      saturday: { open: '00:00', close: '23:59' },
      sunday: { open: '06:00', close: '02:00' },
    },
    work_score: 6.8,
    late_night_score: 9.2,
    wifi_score: 6.0,
    outlet_score: 7.0,
    noise_score: 6.0,
    seating_score: 6.0,
    has_wifi: true,
    has_outlets: true,
    laptop_friendly: true,
    has_bathroom: true,
    has_food: true,
    has_drinks: true,
    noise_level: 'moderate',
    seating_comfort: 'fair',
    vibe_tags: ['late night', 'diner', 'counter seating', '24hr weekends'],
    notes: 'Classic diner energy late night. Wifi works. Counter outlets available.',
    status: 'approved',
    submitted_by: null,
    created_at: new Date().toISOString(),
    last_verified_at: null,
    workability_score: null,
    workability_reasoning: null,
    workability_scored_at: null,
    updated_at: new Date().toISOString(),
  },
  {
    id: '7',
    name: 'Intelligentsia Wicker Park',
    slug: 'intelligentsia-wicker-park-chicago',
    type: 'coffee_shop',
    address: '1850 W North Ave, Chicago, IL 60622',
    city: 'Chicago',
    neighborhood: 'Wicker Park',
    lat: 41.910201,
    lng: -87.677801,
    google_place_id: null,
    photos: [
      { url: 'https://images.unsplash.com/photo-1521017432531-fbd92d768814?w=800', caption: 'Interior' },
    ],
    hours: {
      monday: { open: '06:30', close: '21:00' },
      tuesday: { open: '06:30', close: '21:00' },
      wednesday: { open: '06:30', close: '21:00' },
      thursday: { open: '06:30', close: '21:00' },
      friday: { open: '06:30', close: '21:00' },
      saturday: { open: '07:00', close: '21:00' },
      sunday: { open: '07:00', close: '20:00' },
    },
    work_score: 8.7,
    late_night_score: 5.5,
    wifi_score: 9.0,
    outlet_score: 8.0,
    noise_score: 8.0,
    seating_score: 9.0,
    has_wifi: true,
    has_outlets: true,
    laptop_friendly: true,
    has_bathroom: true,
    has_food: false,
    has_drinks: true,
    noise_level: 'quiet',
    seating_comfort: 'excellent',
    vibe_tags: ['specialty coffee', 'architect crowd', 'quiet', 'great wifi'],
    notes: 'Seriously good wifi. Beautiful buildout. Not a place to take calls.',
    status: 'approved',
    submitted_by: null,
    created_at: new Date().toISOString(),
    last_verified_at: null,
    workability_score: null,
    workability_reasoning: null,
    workability_scored_at: null,
    updated_at: new Date().toISOString(),
  },
  {
    id: '8',
    name: 'The Allis at Soho House',
    slug: 'the-allis-soho-house-chicago',
    type: 'bar',
    address: '113 N Green St, Chicago, IL 60607',
    city: 'Chicago',
    neighborhood: 'West Loop',
    lat: 41.885601,
    lng: -87.648401,
    google_place_id: null,
    photos: [
      { url: 'https://images.unsplash.com/photo-1470337458703-46ad1756a187?w=800', caption: 'Bar' },
      { url: 'https://images.unsplash.com/photo-1514362545857-3bc16c4c7d1b?w=800', caption: 'Lounge' },
    ],
    hours: {
      monday: { open: '08:00', close: '23:00' },
      tuesday: { open: '08:00', close: '23:00' },
      wednesday: { open: '08:00', close: '00:00' },
      thursday: { open: '08:00', close: '00:00' },
      friday: { open: '08:00', close: '02:00' },
      saturday: { open: '09:00', close: '02:00' },
      sunday: { open: '09:00', close: '22:00' },
    },
    work_score: 7.5,
    late_night_score: 8.0,
    wifi_score: 7.5,
    outlet_score: 8.5,
    noise_score: 6.5,
    seating_score: 9.0,
    has_wifi: true,
    has_outlets: true,
    laptop_friendly: true,
    has_bathroom: true,
    has_food: true,
    has_drinks: true,
    noise_level: 'moderate',
    seating_comfort: 'excellent',
    vibe_tags: ['hotel bar', 'upscale', 'late night', 'good wifi'],
    notes: 'Members club but lobby/bar is semi-public. Excellent seating, great wifi.',
    status: 'approved',
    submitted_by: null,
    created_at: new Date().toISOString(),
    last_verified_at: null,
    workability_score: null,
    workability_reasoning: null,
    workability_scored_at: null,
    updated_at: new Date().toISOString(),
  },
  {
    id: '9',
    name: 'Sightglass Coffee SoMa',
    slug: 'sightglass-soma-sf',
    type: 'coffee_shop',
    address: '270 7th St, San Francisco, CA 94103',
    city: 'San Francisco',
    neighborhood: 'SoMa',
    lat: 37.779401,
    lng: -122.408801,
    google_place_id: null,
    photos: [
      { url: 'https://images.unsplash.com/photo-1493857671505-72967e2e2760?w=800', caption: 'Roastery' },
      { url: 'https://images.unsplash.com/photo-1442512595331-e89e73853f31?w=800', caption: 'Upper level' },
    ],
    hours: {
      monday: { open: '07:00', close: '17:00' },
      tuesday: { open: '07:00', close: '17:00' },
      wednesday: { open: '07:00', close: '17:00' },
      thursday: { open: '07:00', close: '17:00' },
      friday: { open: '07:00', close: '17:00' },
      saturday: { open: '08:00', close: '17:00' },
      sunday: { open: '08:00', close: '17:00' },
    },
    work_score: 9.0,
    late_night_score: 3.0,
    wifi_score: 9.2,
    outlet_score: 9.0,
    noise_score: 7.0,
    seating_score: 8.5,
    has_wifi: true,
    has_outlets: true,
    laptop_friendly: true,
    has_bathroom: true,
    has_food: true,
    has_drinks: true,
    noise_level: 'moderate',
    seating_comfort: 'excellent',
    vibe_tags: ['roastery', 'two floors', 'great outlets', 'tech crowd', 'closes early'],
    notes: 'Two-story roastery with tons of outlets and tables. Closes at 5pm though.',
    status: 'approved',
    submitted_by: null,
    created_at: new Date().toISOString(),
    last_verified_at: null,
    workability_score: null,
    workability_reasoning: null,
    workability_scored_at: null,
    updated_at: new Date().toISOString(),
  },
  {
    id: '10',
    name: 'Epoch Coffee North Loop',
    slug: 'epoch-coffee-north-loop-austin',
    type: 'coffee_shop',
    address: '221 W North Loop Blvd, Austin, TX 78751',
    city: 'Austin',
    neighborhood: 'North Loop',
    lat: 30.319801,
    lng: -97.733601,
    google_place_id: null,
    photos: [
      { url: 'https://images.unsplash.com/photo-1463797221720-6b07e6426c24?w=800', caption: 'Late night interior' },
    ],
    hours: {
      monday: { open: '00:00', close: '23:59' },
      tuesday: { open: '00:00', close: '23:59' },
      wednesday: { open: '00:00', close: '23:59' },
      thursday: { open: '00:00', close: '23:59' },
      friday: { open: '00:00', close: '23:59' },
      saturday: { open: '00:00', close: '23:59' },
      sunday: { open: '00:00', close: '23:59' },
    },
    work_score: 8.8,
    late_night_score: 9.9,
    wifi_score: 8.0,
    outlet_score: 9.5,
    noise_score: 7.0,
    seating_score: 7.5,
    has_wifi: true,
    has_outlets: true,
    laptop_friendly: true,
    has_bathroom: true,
    has_food: true,
    has_drinks: true,
    noise_level: 'moderate',
    seating_comfort: 'good',
    vibe_tags: ['24hr', 'Austin legend', 'laptop friendly', 'late night', 'outdoor patio'],
    notes: 'THE 24-hour coffee spot in Austin. Always busy but always open. Outlets at every table.',
    status: 'approved',
    submitted_by: null,
    created_at: new Date().toISOString(),
    last_verified_at: null,
    workability_score: null,
    workability_reasoning: null,
    workability_scored_at: null,
    updated_at: new Date().toISOString(),
  },
  {
    id: '11',
    name: 'Bennu Coffee East 6th',
    slug: 'bennu-coffee-6th-austin',
    type: 'coffee_shop',
    address: '1607 E 6th St, Austin, TX 78702',
    city: 'Austin',
    neighborhood: 'East Austin',
    lat: 30.260901,
    lng: -97.720001,
    google_place_id: null,
    photos: [
      { url: 'https://images.unsplash.com/photo-1511920170033-f8396924c348?w=800', caption: 'Outdoor area' },
    ],
    hours: {
      monday: { open: '00:00', close: '23:59' },
      tuesday: { open: '00:00', close: '23:59' },
      wednesday: { open: '00:00', close: '23:59' },
      thursday: { open: '00:00', close: '23:59' },
      friday: { open: '00:00', close: '23:59' },
      saturday: { open: '00:00', close: '23:59' },
      sunday: { open: '00:00', close: '23:59' },
    },
    work_score: 8.5,
    late_night_score: 9.9,
    wifi_score: 8.5,
    outlet_score: 8.5,
    noise_score: 7.0,
    seating_score: 7.5,
    has_wifi: true,
    has_outlets: true,
    laptop_friendly: true,
    has_bathroom: true,
    has_food: true,
    has_drinks: true,
    noise_level: 'moderate',
    seating_comfort: 'good',
    vibe_tags: ['24hr', 'east austin', 'dog friendly', 'outdoor seating', 'late night'],
    notes: 'Also 24 hours. East Austin vibe. Dog-friendly patio. Solid wifi.',
    status: 'approved',
    submitted_by: null,
    created_at: new Date().toISOString(),
    last_verified_at: null,
    workability_score: null,
    workability_reasoning: null,
    workability_scored_at: null,
    updated_at: new Date().toISOString(),
  },
  {
    id: '12',
    name: 'Victrola Coffee Roasters',
    slug: 'victrola-coffee-capitol-hill-seattle',
    type: 'coffee_shop',
    address: '310 E Pike St, Seattle, WA 98122',
    city: 'Seattle',
    neighborhood: 'Capitol Hill',
    lat: 47.614801,
    lng: -122.326501,
    google_place_id: null,
    photos: [
      { url: 'https://images.unsplash.com/photo-1447933601403-0c6688de566e?w=800', caption: 'Interior' },
      { url: 'https://images.unsplash.com/photo-1517231925375-bf2cb42917a5?w=800', caption: 'Roaster' },
    ],
    hours: {
      monday: { open: '06:30', close: '19:00' },
      tuesday: { open: '06:30', close: '19:00' },
      wednesday: { open: '06:30', close: '19:00' },
      thursday: { open: '06:30', close: '19:00' },
      friday: { open: '06:30', close: '19:00' },
      saturday: { open: '07:00', close: '19:00' },
      sunday: { open: '07:00', close: '18:00' },
    },
    work_score: 8.5,
    late_night_score: 4.0,
    wifi_score: 8.0,
    outlet_score: 8.0,
    noise_score: 7.5,
    seating_score: 7.5,
    has_wifi: true,
    has_outlets: true,
    laptop_friendly: true,
    has_bathroom: true,
    has_food: false,
    has_drinks: true,
    noise_level: 'quiet',
    seating_comfort: 'good',
    vibe_tags: ['roastery', 'quiet', 'serious coffee', 'laptop crowd'],
    notes: 'Seattle staple. Great pour-overs. Calm atmosphere during weekday mornings.',
    status: 'approved',
    submitted_by: null,
    created_at: new Date().toISOString(),
    last_verified_at: null,
    workability_score: null,
    workability_reasoning: null,
    workability_scored_at: null,
    updated_at: new Date().toISOString(),
  },
  {
    id: '13',
    name: 'Sightglass New Montgomery',
    slug: 'sightglass-new-montgomery-sf',
    type: 'coffee_shop',
    address: '301 Howard St, San Francisco, CA 94105',
    city: 'San Francisco',
    neighborhood: 'Financial District',
    lat: 37.788801,
    lng: -122.395701,
    google_place_id: null,
    photos: [
      { url: 'https://images.unsplash.com/photo-1498804103079-a6351b050096?w=800', caption: 'Street view' },
    ],
    hours: {
      monday: { open: '06:30', close: '19:00' },
      tuesday: { open: '06:30', close: '19:00' },
      wednesday: { open: '06:30', close: '19:00' },
      thursday: { open: '06:30', close: '19:00' },
      friday: { open: '06:30', close: '19:00' },
      saturday: { open: '07:00', close: '17:00' },
      sunday: null,
    },
    work_score: 8.0,
    late_night_score: 3.5,
    wifi_score: 8.5,
    outlet_score: 8.0,
    noise_score: 8.0,
    seating_score: 7.5,
    has_wifi: true,
    has_outlets: true,
    laptop_friendly: true,
    has_bathroom: true,
    has_food: true,
    has_drinks: true,
    noise_level: 'quiet',
    seating_comfort: 'good',
    vibe_tags: ['financial district', 'quiet', 'no weekends', 'quick turnover'],
    notes: 'Dead quiet on weekdays. Good wifi. Closed Sundays.',
    status: 'approved',
    submitted_by: null,
    created_at: new Date().toISOString(),
    last_verified_at: null,
    workability_score: null,
    workability_reasoning: null,
    workability_scored_at: null,
    updated_at: new Date().toISOString(),
  },
]

export const DEMO_CITIES = ['Austin', 'Chicago', 'Los Angeles', 'New York City', 'San Francisco', 'Seattle']
